# cosmetics
# font_family Iosevka Nerd Font
font_family DejaVu Sans Mono
font_size 17.0

text_antialias true
text_autohint true

cursor_shape block
cursor_shape_unfocused block
cursor_blink_interval 0

disable_ligatures always

mouse_hide_wait -1

enable_audio_bell no

shell_integration disabled
confirm_os_window_close 0

window_padding 0
margin 0

# colors
background #080808

# keybinds
map ctrl+equal change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size 0
