source = ~/.nix/configs/hypr/keymap.conf
source = ~/.nix/configs/hypr/other.conf
source = ~/.nix/configs/hypr/monitors.conf
source = ~/.nix/configs/hypr/animations.conf
source = ~/.nix/configs/hypr/rules.conf
source = ~/.nix/configs/hypr/general.conf
source = ~/.nix/configs/hypr/startup.conf
source = ~/.nix/configs/hypr/locals.conf
