# telegram media viewer float and pinned
windowrulev2 = float, class:(org.telegram.desktop) title:(Media viewer)
windowrulev2 = noanim, class:(org.telegram.desktop) title:(Media viewer)

# flameshot
windowrulev2 = float, class:(flameshot)
windowrulev2 = noanim, class:(flameshot)
windowrulev2 = center 1, class:(flameshot)

# transparency for kitty
windowrulev2 = opacity 0.9 override 0.9 override 0.9 override, class:^(.*kitty.*)$

# thunar file picker
# upload
windowrulev2 = float, initialTitle:^(.*Upload.*)$
windowrulev2 = size 900 600, initialTitle:^(.*Upload.*)$
windowrulev2 = center 1, initialTitle:^(.*Upload.*)$
# save
windowrulev2 = float, initialTitle:^(.*Save.*)$
windowrulev2 = size 900 600, initialTitle:^(.*Save.*)$
windowrulev2 = center 1, initialTitle:^(.*Save.*)$
# select
windowrulev2 = float, initialTitle:^(.*Select.*)$
windowrulev2 = size 900 600, initialTitle:^(.*Select.*)$
windowrulev2 = center 1, initialTitle:^(.*Select.*)$
# <files> pattern
windowrulev2 = float, initialTitle:^(.*File.*)$
windowrulev2 = size 900 600, initialTitle:^(.*File.*)$
windowrulev2 = center 1, initialTitle:^(.*File.*)$
windowrulev2 = float, initialTitle:^(.*file.*)$
windowrulev2 = size 900 600, initialTitle:^(.*file.*)$
windowrulev2 = center 1, initialTitle:^(.*file.*)$
# links (primarily opened by teams desktop app)
windowrulev2 = float, class:(xdg-desktop-portal-gtk) initialTitle:^(https://.*)$
windowrulev2 = size 900 600, class:(xdg-desktop-portal-gtk) initialTitle:^(https://.*)$
windowrulev2 = center 1, class:(xdg-desktop-portal-gtk) initialTitle:^(https://.*)$

windowrulev2 = suppressevent maximize, class:.*
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
